matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "release/Altitude-Metrix-Wallet-win32-x64.exe"
          - "release/Altitude-Metrix-Wallet-linux-x64.AppImage"
          - "release/Altitude-Metrix-Wallet-mac-x64.dmg"
        skip_cleanup: true
        draft: true
        on:
          tags: true

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - npm run electron:mac
  - npm run electron:linux
  - npm run electron:windows
  - mv release/Altitude-Metrix-Wallet-win32.exe release/Altitude-Metrix-Wallet-win32-x64.exe

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

if: tag IS present
