
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
    faReceipt,
    faWallet,
    faNetworkWired,
    faColumns,
    faWifi,
    faClock,
    faLayerGroup,
    faLock,
    faUnlock,
    faSignInAlt,
    faSignOutAlt,
    faPiggyBank,
    faExchangeAlt,
    faCopy,
    faTimes,
    faPlus,
    faCode,
    faCoins,
    faDatabase,
    faCheckCircle,
    faTimesCircle,
    faCircleNotch,
    faLockOpen,
    faAddressBook,
    faArrowLeft,
    faArrowRight,
    faTrash,
    faSave,
    faHandPointer,
    faToggleOff,
    faToggleOn,
    faArrowDown,
    faArrowUp,
    faSpinner,
    faExclamationCircle,
    faLink,
    faChevronDown,
    faChevronRight
} from '@fortawesome/free-solid-svg-icons';


export function setupIcons() {
    // only add used icons to avoid bloat
    library.add(
        faWallet,
        faReceipt,
        faNetworkWired,
        faColumns,
        faWifi,
        faClock,
        faLayerGroup,
        faLock,
        faUnlock,
        faSignInAlt,
        faSignOutAlt,
        faPiggyBank,
        faExchangeAlt,
        faCopy,
        faTimes,
        faPlus,
        faCode,
        faCoins,
        faDatabase,
        faCheckCircle,
        faTimesCircle,
        faCircleNotch,
        faLockOpen,
        faAddressBook,
        faArrowLeft,
        faArrowRight,
        faTrash,
        faSave,
        faHandPointer,
        faToggleOff,
        faToggleOn,
        faArrowDown,
        faArrowUp,
        faSpinner,
        faExclamationCircle,
        faLink,
        faChevronDown,
        faChevronRight
    );
}