# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron Package Test

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches: 
      - "master"
      - "develop"

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-13
    strategy:
      matrix:
        node: [20]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - name: Build Binaries
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ vars.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
            npm run electron:mac
            npm run electron:linux
            npm run electron:windows
            mv release/Altitude-Metrix-Wallet-win32.exe release/Altitude-Metrix-Wallet-win32-x64.exe
            npm run electron:windows32
            mv release/Altitude-Metrix-Wallet-win32.exe release/Altitude-Metrix-Wallet-win32-x86.exe
